config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  root "public_pages#main_home"

  get "/about", to: "public_pages#about"
  get "/contact", to: "public_pages#contact"
  get "/features", to: "public_pages#features"
  get "/privacy", to: "public_pages#privacy"
  get "/terms-of-use", to: "public_pages#terms"
  get "/report-issues", to: "public_pages#report_issues"


  get "/signup", to: "authentication#sign_up", as: :signup
  get "/login", to: "authentication#login_form", as: :login
  post "/login", to: "authentication#handle_log_in", as: :handle_login
  get "/logout", to: "authentication#log_out", as: :logout
  get "/forgot-password", to: "authentication#forgot_pw", as: :forgot_pw
  post "/forgot-password", to: "authentication#handle_forgot_pw", as: :handle_forgot_pw
  get "/reset-password", to: "authentication#reset_pw", as: :reset_pw

  post "/request_otp", to: "otp#create"
  get "/otp-verification", to: "otp#input", as: :otp_input
  post "/verify-otp",  to: "otp#verify", as: :verify_otp
  post "/resend-otp",  to: "otp#resend"
  # get "/otp", to: "otp#new"


  resources :posts, only: [ :index, :show ]
  resources :users

  scope module: "landlord_area" do
    resources :landlords, shallow: true do
      resources :dashboard, :posts
      resources :houses, shallow: true do
        resources :rooms, :invoices, :vehicles, :contracts
      end
    end
  end

  scope module: "tenant_area" do
    resources :tenants, shallow: true do
      resources :dashboard, :posts
    end
  end

  scope module: "admin_area" do
    resources :admin, shallow: true do
      resources :dashboard
      resources :houses
    end
  end
end

app/models/concerns/otp.rb
module Otp
  extend ActiveSupport::Concern

  OTP_EXPIRY = 5.minutes

  def generate_otp!
    self.otp_code = SecureRandom.random_number(1_000_000).to_s.rjust(6, "0")
    self.otp_sent_at = Time.current

    save!(validate: false)

    otp_code
  end


  def otp_expired?
    otp_sent_at.nil? || otp_sent_at < OTP_EXPIRY.ago
  end

  def clear_otp
    self.otp_code = nil
    self.tel_verified_at = Time.current

    save!(validate: false)
  end
end

app/controllers/otp_controller.rb
class OtpController < ApplicationController
  def input
    render "otp_input", locals: { tel: session[:pending_tel] }
  end

  def create
    result = PhoneVerification.new(params[:tel], params[:role]).request_otp
    session[:pending_tel] = result.user.tel
    redirect_to verify_otp_path
  end

  def resend
    verification = PhoneVerification.new(tel: session[:pending_tel], role: session[:pending_role])
    verification.resend_otp
    flash.now[:notice] = t("messages.resend_success")
    render "otp_input", locals: { tel: session[:pending_tel] }
  end

  def verify
    service = PhoneVerification.new(
      tel: session[:pending_tel],
      role: session[:pending_role]
    )

    Rails.logger.info "Input OTP in after form submission: #{params[:otp]}"

    result = service.verify_otp(params[:otp])

    respond_to do |format|
      message = ""
      case result.status
      when :verified
        if session[:is_reset_pw]
          session[:verified_tel] = session[:pending_tel]
          redirect_to reset_pw_path
        else
          clear_session_keys(:pending_role, :pending_tel)
          log_in(result.user)

          flash[:notice] = t("messages.signup_success")
          redirect_to root_path
        end
        return

      when :otp_verification_failed
        message = t("errors.otp_failed")
      when :expired_otp
        message = t("errors.expired_otp")
      else
        message = t("errors.wrong_otp")
      end

      flash.now[:alert] = message
      format.turbo_stream do
        render turbo_stream: turbo_stream.update(
          "flash",
          partial: "layouts/shared_components/flash_message"
        )
      end

      flash.discard
    end
  end
end

app/views/otp/otp_input.html.erb
<div class="custom card my-5 mx-auto px-5 py-4">
    <div class="card-body d-flex align-items-center flex-column gap-3">
        <h1 class="card-title text-center"><%=t('form.profile.otp_title').upcase %></h1>
        <p class="card-text"><%=t('form.profile.check_tel') %></p>
        <p class="card-text"><%=t('form.profile.check_tel_html', tel: tel) %></p>
        <p class="card-text otp-valid"><%=t('form.profile.otp_valid') %></p>

        <!-- Timer -->
        <div class="text-center fw-bold timer"
            data-controller="otp-timer"
            data-otp-timer-duration-value="300">

            <span data-otp-timer-target="time"></span>
        </div>

        <!-- Input boxes-->
        <div class="d-flex gap-2 justify-content-center otp-inputs"
            data-controller="otp"
            data-otp-length-value="6">

            <%= form_with url: verify_otp_path, method: :post, local: false, 
                            data: { otp_target: "form" }, 
                            class: "d-flex flex-column gap-3 mb-5 align-items-center" do |f| %>
                
                <%# The hidden field that will hold the combined 6 digits %>
                <%= f.hidden_field :otp, data: { otp_target: "hidden" } %>

                <div class="d-flex gap-2">
                <% 6.times do |i| %>
                    <input
                    type="text"
                    inputmode="numeric"
                    maxlength="1"
                    autocomplete="one-time-code" <%# Helps mobile browsers suggest the SMS code %>
                    class="otp-box form-control"
                    data-otp-target="digit"
                    data-action="input->otp#input keydown->otp#keydown paste->otp#paste"
                    <%= "autofocus" if i == 0 %>
                    >
                <% end %>
                </div>

                <button type="submit" class="custom-primary-btn"><%= t('form.profile.verify') %></button>
            <% end %>
        </div>


        <div class="field-info mb-2 d-flex align-items-center gap-1">
            <span class="material-symbols-outlined">info</span>
            <small><%= t('form.profile.otp_note') %></small>
        </div>

        <%= button_to t('form.profile.resend_otp'), resend_otp_path, data: { turbo: false }, class:"custom-secondary-btn" %>
        <%= link_to :back, class: "mx-auto d-flex align-items-center forgot-pw link" do%>
            <span class="material-symbols-outlined">arrow_left_alt</span>
            <%=t('turn_back')%>
        <%end%>
    </div>
</div>