config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  root "public_pages#main_home"

  get "/about", to: "public_pages#about"
  get "/contact", to: "public_pages#contact"
  get "/features", to: "public_pages#features"
  get "/privacy", to: "public_pages#privacy"
  get "/terms-of-use", to: "public_pages#terms"
  get "/report-issues", to: "public_pages#report_issues"


  get "/signup", to: "authentication#sign_up", as: :signup
  get "/login", to: "authentication#login_form", as: :login
  post "/login", to: "authentication#handle_log_in", as: :handle_login
  get "/logout", to: "authentication#log_out", as: :logout
  get "/forgot-password", to: "authentication#forgot_pw", as: :forgot_pw
  post "/forgot-password", to: "authentication#handle_forgot_pw", as: :handle_forgot_pw
  get "/reset-password", to: "authentication#reset_pw", as: :reset_pw

  post "/request_otp", to: "otp#create"
  get "/otp-verification", to: "otp#input", as: :otp_input
  post "/verify-otp",  to: "otp#verify", as: :verify_otp
  post "/resend-otp",  to: "otp#resend"
  # get "/otp", to: "otp#new"


  resources :posts, only: [ :index, :show ]
  resources :users

  scope module: "landlord_area" do
    resources :landlords, shallow: true do
      resources :dashboard, :posts
      resources :houses, shallow: true do
        resources :rooms, :invoices, :vehicles, :contracts
      end
    end
  end

  scope module: "tenant_area" do
    resources :tenants, shallow: true do
      resources :dashboard, :posts
    end
  end

  scope module: "admin_area" do
    resources :admin, shallow: true do
      resources :dashboard
      resources :houses
    end
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def sign_up
    @user = User.new
  end

  def login_form
    if logged_in?
      redirect_to root_path
      return
    end

    @user = User.new
    render "authentication/log_in"
  end

  def log_out
    destroy_session
    flash[:notice] = t("messages.logout_success")
    redirect_to root_path
  end

  def forgot_pw
    @user = User.new
  end

  def reset_pw
    tel = session[:verified_tel]

    unless tel
      redirect_to forgot_pw_path, alert: t("errors.session_expired")
      return
    end

    @user = User.kept.find_by(tel: tel, role: session[:pending_role])
  end


  def handle_log_in
    user_params = login_params
    existing_acc = User.find_acc(user_params[:tel], user_params[:role])
    message = nil

    if existing_acc.nil?
      message = t("errors.unregistered")
    elsif !existing_acc.active?
      message = t("errors.inactive_acc")
    elsif !existing_acc.authenticate(user_params[:password])
      message = t("errors.wrong_pw")
    else
      log_in(existing_acc)
      flash[:notice] = t("messages.login_success")
      # If you want to redirect after login, you can do it here
      return redirect_to root_path
    end

    # For invalid login: render flash in current view via Turbo
    flash.now[:alert] = message

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update(
          "flash",
          partial: "layouts/shared_components/flash_message"
        )
      end

      format.html { render :new } # fallback for non-Turbo requests
    end
  end

  def handle_forgot_pw
    user_params = login_params
    existing_acc = User.find_acc(user_params[:tel], user_params[:role])
    message = nil

    if existing_acc.nil?
      message = t("errors.unregistered")
    elsif !existing_acc.active?
      message = t("errors.inactive_acc")
    else
      #
      result = PhoneVerification.new(
        tel: user_params[:tel],
        role: user_params[:role]
      )
      result.create_otp(existing_acc)
      session[:pending_tel] = existing_acc.tel
      session[:pending_role] = existing_acc.role
      session[:is_reset_pw] = true
      redirect_to otp_input_path, notice: t("messages.send_otp")
      return
    end

    flash.now[:alert] = message

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update(
          "flash",
          partial: "layouts/shared_components/flash_message"
        )
      end

      format.html { render :new } # fallback for non-Turbo requests
    end
  end


  private

  def login_params
    params.require(:user).permit(:tel, :password, :role)
  end
end

app/views/authentication/forgot_pw.html.erb
<% content_for :title, "Forgot Password" %>

<div class="custom card px-5 py-4 m-5 mx-auto">
    <div class="card-body d-flex flex-column gap-3">
        <h1 class="card-title text-center"><%=t('form.profile.forgot_pw_title').upcase %></h1>

        <!-- TODO handle-->
        <%= form_with model: @user, url: handle_forgot_pw_path, local: true,
              class: "signup-form d-flex align-items-center justify-content-center flex-column gap-4" do |f| %>

            <!-- Role -->
            <div class="form-group w-100 gap-2 d-flex flex-column align-items-center mb-2">
                <%= f.label :role, class: "form-label" do %>
                <%= t("form.profile.role") %>:
                <span class="asterisk">*</span>
                <% end %>

                <div class="d-flex gap-4 w-100">
                <label class="d-flex align-items-center gap-2">
                    <%= f.radio_button :role, "tenant", checked: true %>
                    <%= t("common.role.tenant") %>
                </label>

                <label class="d-flex align-items-center gap-2">
                    <%= f.radio_button :role, "landlord" %>
                    <%= t("common.role.landlord") %>
                </label>
                </div>
            </div>


            <!-- Tel -->
            <div class="form-group w-100">
                <%= f.label :tel, class: "form-label" do %>
                    <%= t("form.profile.tel") %>:<span class="asterisk">*</span>
                <% end %>

                <%= f.telephone_field :tel,
                    minlength: 10,
                    maxlength: 10,
                    required: true,
                    class: "form-control",
                    placeholder: t("form.profile.tel_login_placeholder") %>
            </div>

            <%= f.submit t("form.profile.send_otp"), class: "mx-auto custom-primary-btn" %>

        <% end %>

        <%= link_to :back, class: "mx-auto d-flex align-items-center forgot-pw link" do%>
            <span class="material-symbols-outlined">arrow_left_alt</span>
            <%=t('turn_back')%>
        <%end%>

        </div>
    </div>
</div>

app/views/authentication/log_in.html.erb
<% content_for :title, "Login" %>

<div class="d-flex w-100 h-100 signup-container">
    <%=image_tag "signup-bg.png", alt: "Sign Up Background", class: "align-self-stretch signup-bg" %>
    <div class="form-wrapper d-flex flex-column gap-4 align-items-center py-4 flex-fill">
        <div class="greeting">
            <p class="mb-2 text-center"><%= t('common.welcome.back') %></p>
            <p class="text-center">LEANHOUSE !</p>
        </div>
        <h1><%= t("common.auth.sign_up").upcase %></h1>

        <%= form_with(model: @user, url: handle_login_path, method: :post, class: "signup-form w-100 d-flex align-items-center justify-content-center flex-column gap-4") do |f| %>

            <!-- Role selection -->
            <div data-controller="role-selector" class="form-group gap-2 d-flex flex-column align-items-center mb-2">
                <%= f.hidden_field :role, data: { role_selector_target: "input" } %>
                <%= f.label :role, class: "form-label" do %>
                    <%= t('form.profile.role') + ": "%> 
                    <span class="asterisk">*</span>
                <% end %>

                <div class="d-flex gap-3">
                    <div
                        class="role-option selected d-flex flex-column align-items-center gap-1 px-2 py-1"
                        data-action="click->role-selector#select"
                        data-role-selector-value="tenant"
                    >
                        <%= image_tag "tenant-icon.png", alt: "Tenant Icon" %>
                        <p><%= t('common.role.tenant') %></p>
                    </div>

                    <div
                        class="role-option d-flex flex-column align-items-center gap-1 px-2 py-1"
                        data-action="click->role-selector#select"
                        data-role-selector-value="landlord"
                    >
                        <%= image_tag "landlord-icon.png", alt: "Landlord Icon" %>
                        <p><%= t('common.role.landlord') %></p>
                    </div>
                </div>
            </div>

            <!-- Tel -->
            <div class="form-group">
                <%= f.label :tel, t('form.profile.tel') + ":", class: "form-label" %> <span class="asterisk">*</span>
                <%= f.telephone_field :tel, 
                    class: "form-control", 
                    placeholder: t('form.profile.tel_login_placeholder'), 
                    minlength: 10, maxlength: 10, required: true, autofocus: true %>
            </div>

            <!-- Password -->
            <div class="form-group" data-controller="form">
                <%= f.label :password, class: "form-label" do%>
                        <%= t('form.profile.password') +  ": "%>
                        <span class="asterisk">*</span>
                <% end %>

                <div class="position-relative">
                    <%= f.password_field :password, maxlength: 72, required: true,
                        class: "form-control pe-5 #{invalid_class(@user, :password)}",
                        placeholder: t('form.profile.pw_placeholder'),
                        data: {
                            form_target: "input",
                            action: "input->form#update"
                        } 
                    %>

                    <span class="eye position-absolute me-2 top-50 end-0 translate-middle-y material-symbols-outlined password-toggle" 
                            data-action="click->form#togglePasswordVisibility">
                        visibility
                    </span>
                </div>
            </div>


            <%= link_to t('form.profile.forgot_pw'), forgot_pw_path, class: "forgot-pw link" %>

            <%= f.submit t("common.auth.log_in"), class: "mx-auto custom-primary-btn" %>
        <% end %>

        <div class="d-flex flex-wrap gap-2"> 
            <%= t('form.profile.not_have_acc')%> 
            <%= link_to t('form.profile.reg_now'), login_path, class: "fw-bold link" %> 
        </div>
    </div>
</div>

app/views/authentication/reset_pw.html.erb
<% content_for :title, "Reset Password" %>

<div class="custom card px-5 py-4 m-5 mx-auto">
    <div class="card-body d-flex flex-column gap-3">
        <h1 class="card-title text-center"><%=t('form.profile.reset_pw').upcase %></h1>

        <!-- TODO handle-->
        <%= form_with model: @user, local: true, 
                    class:"signup-form w-100 d-flex align-items-center flex-column gap-4" do |form| %>

             <!-- Password -->
            <div class="form-group w-100" data-controller="form">
                <%= form.label :password, class: "form-label d-flex justify-content-between" do%>
                    <div>
                        <%= t('form.profile.password') +  ": "%>
                        <span class="asterisk">*</span>
                    </div>

                    <small class="counter-text">
                        <span data-form-target="charCount">0</span>
                    </small>
                <% end %>

                <div class="position-relative">
                    <%= form.password_field :password, minLength: 8, maxLength: 72, required: true,
                        class: "form-control pe-5 #{invalid_class(@user, :password)}",
                        placeholder: t('form.profile.pw_placeholder'),
                        data: {
                            form_target: "input",
                            action: "input->form#update"
                        } 
                    %>

                    <span class="eye position-absolute me-2 top-50 end-0 translate-middle-y material-symbols-outlined password-toggle" 
                            data-action="click->form#togglePasswordVisibility">
                        visibility
                    </span>
                </div>

                <%= field_error(@user, :password) %>

                <div class="field-info m-2 d-flex align-items-center gap-1">
                    <span class="material-symbols-outlined">info</span>
                    <p><%= t('form.profile.required_pw') %></p>
                </div>

                <ul class="field-info d-flex flex-column gap-1 mb-1">
                    <li><%= t('form.profile.pw_length')%></li>
                    <li><%= t('form.profile.pw_letters')%></li>
                    <li><%= t('form.profile.pw_numbers')%></li>
                </ul>
            </div>
            

            <div class="form-group w-100" data-controller="form">
                <%= form.label :password_confirmation, class: "form-label d-flex justify-content-between" do%>
                    <div>
                        <%= t('form.profile.password_confirmation') +  ": "%>
                        <span class="asterisk">*</span>
                    </div>

                    <small class="counter-text">
                        <span data-form-target="charCount">0</span>
                    </small>
                <% end %>

                <div class="position-relative">
                    <%= form.password_field :password_confirmation, minLength: 8, maxLength: 72, required: true,
                        class: "form-control pe-5 #{invalid_class(@user, :password_confirmation)}",
                        placeholder: t('form.profile.pw_cf_placeholder'),
                        data: {
                            form_target: "input",
                            action: "input->form#update"
                        } 
                    %>

                    <span class="eye position-absolute me-2 top-50 end-0 translate-middle-y material-symbols-outlined password-toggle" 
                            data-action="click->form#togglePasswordVisibility">
                        visibility
                    </span>
                </div>

                <%= field_error(@user, :password_confirmation) %>
            </div>

             <%= form.submit t("form.save"), class: "mx-auto custom-primary-btn" %>
        <%end%>

        <%= link_to :back, class: "mx-auto d-flex align-items-center forgot-pw link" do%>
            <span class="material-symbols-outlined">arrow_left_alt</span>
            <%=t('turn_back')%>
        <%end%>

        </div>
    </div>
</div>

app/views/authentication/sign_up.html.erb
<% content_for :title, "Sign Up" %>

<div class="d-flex w-100 h-100 signup-container">
    <%=image_tag "signup-bg.png", alt: "Sign Up Background", class: "align-self-stretch signup-bg" %>
    <div class="form-wrapper d-flex flex-column gap-4 align-items-center py-4 flex-fill">
        <div class="greeting">
            <p class="mb-2 text-center"><%= t('common.welcome.greeting') %></p>
            <p class="text-center">LEANHOUSE !</p>
        </div>
        <h1><%= t("common.auth.sign_up").upcase %></h1>

        <%# Form is handled at user#create %>
        <%= form_with model: @user, local: true, 
                    class:"signup-form d-flex align-items-center flex-column gap-4" do |form| %>

            <!-- Role selection -->
            <div data-controller="role-selector" class="form-group gap-2 d-flex flex-column align-items-center mb-2">
                <%= form.hidden_field :role, data: { role_selector_target: "input" } %>
                <%= form.label :role, class: "form-label" do %>
                    <%= t('form.profile.role') + ": "%> 
                    <span class="asterisk">*</span>
                <% end %>

                <div class="d-flex gap-3">
                    <div
                        class="role-option selected d-flex flex-column align-items-center gap-1 px-2 py-1"
                        data-action="click->role-selector#select"
                        data-role-selector-value="tenant"
                    >
                        <%= image_tag "tenant-icon.png", alt: "Tenant Icon" %>
                        <p><%= t('common.role.tenant') %></p>
                    </div>

                    <div
                        class="role-option d-flex flex-column align-items-center gap-1 px-2 py-1"
                        data-action="click->role-selector#select"
                        data-role-selector-value="landlord"
                    >
                        <%= image_tag "landlord-icon.png", alt: "Landlord Icon" %>
                        <p><%= t('common.role.landlord') %></p>
                    </div>
                </div>
            </div>

            <!-- Tel -->   
            <div class="form-group" data-controller="form">
                <%= form.label :tel , class: "form-label d-flex justify-content-between" do%>
                    <div>
                        <%= t('form.profile.tel') +  ": "%>
                        <span class="asterisk">*</span>
                    </div>

                    <small class="counter-text">
                        <span data-form-target="charCount">0</span>
                    </small>
                <% end %>

                <div class="field-info mb-2 d-flex align-items-center gap-1">
                    <span class="material-symbols-outlined">info</span>
                    <small><%= t('form.profile.zalo') %></small>
                </div>

                <%= form.telephone_field :tel, minlength: 10, maxlength: 10, class: "mb-1 form-control #{invalid_class(@user, :tel)}", 
                    placeholder: t('form.profile.tel_placeholder'), required: true, autofocus: true,
                    data: {
                        form_target: "input",
                        action: "input->form#update"
                    } 
                %>
                <%= field_error(@user, :tel) %>
            </div>


            <!-- Password -->
            <div class="form-group" data-controller="form">
                <%= form.label :password, class: "form-label d-flex justify-content-between" do%>
                    <div>
                        <%= t('form.profile.password') +  ": "%>
                        <span class="asterisk">*</span>
                    </div>

                    <small class="counter-text">
                        <span data-form-target="charCount">0</span>
                    </small>
                <% end %>

                <div class="position-relative">
                    <%= form.password_field :password, minlength: 8, maxlength: 72, required: true,
                        class: "form-control pe-5 #{invalid_class(@user, :password)}",
                        placeholder: t('form.profile.pw_placeholder'),
                        data: {
                            form_target: "input",
                            action: "input->form#update"
                        } 
                    %>

                    <span class="eye position-absolute me-2 top-50 end-0 translate-middle-y material-symbols-outlined password-toggle" 
                            data-action="click->form#togglePasswordVisibility">
                        visibility
                    </span>
                </div>

                <%= field_error(@user, :password) %>

                <div class="field-info m-2 d-flex align-items-center gap-1">
                    <span class="material-symbols-outlined">info</span>
                    <p><%= t('form.profile.required_pw') %></p>
                </div>

                <ul class="field-info d-flex flex-column gap-1 mb-1">
                    <li><%= t('form.profile.pw_length')%></li>
                    <li><%= t('form.profile.pw_letters')%></li>
                    <li><%= t('form.profile.pw_numbers')%></li>
                </ul>
            </div>
            

            <div class="form-group" data-controller="form">
                <%= form.label :password_confirmation, class: "form-label d-flex justify-content-between" do%>
                    <div>
                        <%= t('form.profile.password_confirmation') +  ": "%>
                        <span class="asterisk">*</span>
                    </div>

                    <small class="counter-text">
                        <span data-form-target="charCount">0</span>
                    </small>
                <% end %>

                <div class="position-relative">
                    <%= form.password_field :password_confirmation, minlength: 8, maxlength: 72, required: true,
                        class: "form-control pe-5 #{invalid_class(@user, :password_confirmation)}",
                        placeholder: t('form.profile.pw_cf_placeholder'),
                        data: {
                            form_target: "input",
                            action: "input->form#update"
                        } 
                    %>

                    <span class="eye position-absolute me-2 top-50 end-0 translate-middle-y material-symbols-outlined password-toggle" 
                            data-action="click->form#togglePasswordVisibility">
                        visibility
                    </span>
                </div>

                <%= field_error(@user, :password_confirmation) %>
            </div>

            <!-- Fullname -->
            <div class="form-group" data-controller="form">
                <%= form.label :fullname, class: "form-label d-flex justify-content-between" do%>
                    <div>
                        <%= t('form.profile.fullname') +  ": "%>
                        <span class="asterisk">*</span>
                    </div>

                    <small class="counter-text">
                        <span data-form-target="charCount">0</span>
                    </small>
                <% end %>
                
                <%= form.text_field :fullname, maxlength: 50, class: "form-control #{invalid_class(@user, :fullname)}", 
                    placeholder: t('form.profile.fullname_placeholder'), required: true,
                    data: {
                        form_target: "input",
                        action: "input->form#update"
                    } 
                %>

                <%= field_error(@user, :fullname) %>
            </div>

            <!-- Address -->
            <div class="form-group" data-controller="form">
                <%= form.label :address, class: "form-label d-flex justify-content-between" do%>
                    <div>
                        <%= t('form.profile.address') +  ": "%>
                        <span class="asterisk">*</span>
                    </div>

                    <small class="counter-text">
                        <span data-form-target="charCount">0</span>
                    </small>
                <% end %>

                <%= form.text_field :address, maxlength: 100, class: "form-control", 
                    placeholder: t('form.profile.address_placeholder'), required: true,
                    data: {
                        form_target: "input",
                        action: "input->form#update"
                    } 
                %>
            </div>

            <!-- Sex -->
            <div class="form-group d-flex gap-2">
                <%= form.label :sex, class: "form-label" do %>
                    <%= t("form.profile.sex") %>:
                    <span class="asterisk">*</span>
                <% end %>

                <div class="form-check form-check-inline">
                    <%= form.radio_button :sex, "F", class: "form-check-input", required: true %>
                    <%= form.label :sex_f, t("form.profile.female"), class: "form-check-label" %>
                </div>

                <div class="form-check form-check-inline">
                    <%= form.radio_button :sex, "M", class: "form-check-input" %>
                    <%= form.label :sex_m, t("form.profile.male"), class: "form-check-label" %>
                </div>
            </div>

            <!-- Birthday -->
            <div class="form-group d-flex align-items-center gap-3">
                <%= form.label :bday, class: "form-label" do%>
                        <%= t('form.profile.bday') +  ": "%>
                        <span class="asterisk">*</span>
                <% end %>
                <%= form.date_field :bday, max: 15.years.ago.to_date, class: "date form-control", required: true %>
            </div>

            <!-- Terms and Conditions -->
            <div class="form-group mt-3">
                <div class="form-check">
                    <%= form.check_box :terms_accepted, class: "form-check-input" , required: true %>

                    <%= form.label :terms_accepted, class: "form-check-label" do %>
                        <%= t("form.profile.agree_prefix") %>
                        <%= link_to t("common.bar.terms"), terms_of_use_path, target: "_blank", rel: "noopener", class: "link" %>
                        <%= t("and") %>
                        <%= link_to t("common.bar.privacy"), privacy_path, target: "_blank", rel: "noopener", class: "link" %>
                    <% end %>
                </div>
            </div>

            <button type="submit" class="custom-primary-btn"><%= t("form.profile.create_acc") %></button>
        <% end %>
    </div>
</div>