config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  root "public_pages#main_home"

  get "/about", to: "public_pages#about"
  get "/contact", to: "public_pages#contact"
  get "/features", to: "public_pages#features"
  get "/privacy", to: "public_pages#privacy"
  get "/terms-of-use", to: "public_pages#terms"
  get "/report-issues", to: "public_pages#report_issues"


  get "/signup", to: "authentication#sign_up", as: :signup
  get "/login", to: "authentication#login_form", as: :login
  post "/login", to: "authentication#handle_log_in", as: :handle_login
  get "/logout", to: "authentication#log_out", as: :logout
  get "/forgot-password", to: "authentication#forgot_pw", as: :forgot_pw
  post "/forgot-password", to: "authentication#handle_forgot_pw", as: :handle_forgot_pw
  get "/reset-password", to: "authentication#reset_pw", as: :reset_pw

  post "/request_otp", to: "otp#create"
  get "/otp-verification", to: "otp#input", as: :otp_input
  post "/verify-otp",  to: "otp#verify", as: :verify_otp
  post "/resend-otp",  to: "otp#resend"
  # get "/otp", to: "otp#new"


  resources :posts, only: [ :index, :show ]
  resources :users

  scope module: "landlord_area" do
    resources :landlords, shallow: true do
      resources :dashboard, :posts
      resources :houses, shallow: true do
        resources :rooms, :invoices, :vehicles, :contracts
      end
    end
  end

  scope module: "tenant_area" do
    resources :tenants, shallow: true do
      resources :dashboard, :posts
    end
  end

  scope module: "admin_area" do
    resources :admin, shallow: true do
      resources :dashboard
      resources :houses
    end
  end
end

app/views/layouts/shared_components/_additional_nav.html.erb
<div class="secondary-nav px-3 py-2 d-flex gap-3 align-items-center">
    <!-- House card -->
    <div class="card active house-card me-4">
        <div class="card-body px-2 py-1 d-flex gap-1 align-items-center">
            <div>
                 <p class="card-title fw-bold d-flex align-items-center gap-1">
                    <span class="material-symbols-outlined">location_home</span>
                    <%="Title"%>
                </p>
                <p class="card-text line-clamp-2"><%= "Adrress ...... djekje jdadk iorjeio iojeioaj oejdaoj aldjaoi ............ .........."%></p>
            </div>
           
           <!-- Button trigger modal -->
            <button type="button" 
                    class="more-btn d-flex align-items-cente p-1" 
                    data-bs-toggle="modal" data-bs-target="#houseModal"
                    data-bs-placement="top" title="<%=t('common.bar.more_actions')%>"
                >
                <span class="material-symbols-outlined">more_vert</span>
            </button>
        </div>
    </div>

    <!-- Other card -->
    <%=link_to "#", class:"card active other-card" do %>
        <div class="card-body p-0 d-flex flex-column gap-1 align-items-center justify-content-center">
            <%=image_tag "room.png", alt: "Room Icon"%>
            <h5 class="card-title m-0 d-flex align-items-center ">
                <%= t("common.bar.rooms")%>
            </h5>
        </div>
    <%end%>

    <%=link_to "#", class:"card other-card" do %>
        <div class="card-body p-0 d-flex flex-column gap-1 align-items-center justify-content-center">
            <%=image_tag "human-resources.png", alt: "People Icon"%>
            <h5 class="m-0 card-title d-flex align-items-center">
                <%= t("common.bar.tenants")%>
            </h5>
        </div>
    <%end%>

    <%=link_to "#", class:"card other-card" do %>
        <div class="card-body p-0 d-flex flex-column gap-1 align-items-center justify-content-center">
            <%=image_tag "property.png", alt: "Property Icon"%>
            <h5 class="m-0 card-title d-flex align-items-center">
                <%= t("common.bar.properties")%>
            </h5>
        </div>
    <%end%>

    <%=link_to "#", class:"card other-card" do %>
        <div class="card-body p-0 d-flex flex-column gap-1 align-items-center justify-content-center">
            <%=image_tag "home-services.png", alt: "Home services Icon"%>
            <h5 class="m-0 card-title d-flex align-items-center">
                <%= t("common.bar.services")%>
            </h5>
        </div>
    <%end%>

    <%=link_to "#", class:"card other-card" do %>
        <div class="card-body p-0 d-flex flex-column gap-1 align-items-center justify-content-center">
            <%=image_tag "contracts.png", alt: "Contract Icon"%>
            <h5 class="m-0 card-title d-flex align-items-center">
                <%= t("common.bar.contracts")%>
            </h5>
        </div>
    <%end%>

    <%=link_to "#", class:"card other-card" do %>
        <div class="card-body p-0 d-flex flex-column gap-1 align-items-center justify-content-center">
            <%=image_tag "expenses.png", alt: "Invoice Icon"%>
            <h5 class="m-0 card-title d-flex align-items-center">
                <%= t("common.bar.invoices")%>
            </h5>
        </div>
    <%end%>

    <%=link_to "#", class:"card other-card" do %>
        <div class="card-body p-0 d-flex flex-column gap-1 align-items-center justify-content-center">
            <%=image_tag "car.png", alt: "Car Icon"%>
            <h5 class="m-0 card-title d-flex align-items-center">
                <%= t("common.bar.vehicles")%>
            </h5>
        </div>
    <%end%>
</div>

app/views/layouts/shared_components/_auth_box.html.erb
<% if logged_in?%>
    <!--TODO Profile -->
    <div class="dropdown profile-dropdown">
        <button class="dropdown-toggle d-flex align-items-center gap-2" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= display_avatar %>
            <div class="d-flex flex-column align-items-start">
                <p class="fw-bold fullname"><%=format_name(current_user.fullname) %></p>
                <p class="role"><%=get_role%></p>
            </div>
        </button>

        <ul class="dropdown-menu">
             <li><a class="dropdown-item" href="#"><%=t('common.bar.my_profile')%></a></li>
            <% if current_user.role == "landlord" %>
                <li><a class="dropdown-item" href="#"><%=t("common.bar.my_bank_acc")%></a></li>
            <%else%>
                <li><a class="dropdown-item" href="#"><%=t("common.bar.my_vehicle")%></a></li>
                <li><a class="dropdown-item" href="#"><%=t("common.bar.my_saved_post")%></a></li>
            <%end%>
            <li><a class="dropdown-item d-flex gap-1 align-items-center" href="<%=logout_path%>">
                    <%=t("common.auth.log_out")%>
                    <span class="material-symbols-outlined">logout</span>
            </a></li>
        </ul>
    </div>

    <!-- TODO: Notification -->
    <div class="dropdown notification-dropdown">
        <button class="dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <div class="position-relative">
                <span class="material-symbols-filled">notifications</span>
                <div class="notification-badge">3</div>
            </div>
        </button>


        <ul class="dropdown-menu dropdown-menu-end">
            <li><a class="dropdown-item" href="#">Notification 1</a></li>
            <li><a class="dropdown-item" href="#">Notification 2</a></li>
        </ul>
    </div>




<%else%>
    <%= link_to t("common.auth.sign_up"), signup_path, class: "signup-btn"%>

    <%= link_to login_path, class: "login-btn gap-1 d-flex align-items-center" do %>
        <%= t("common.auth.log_in") %>
        <span class="material-symbols-filled">door_open</span>
    <% end %>
<%end%>

app/views/layouts/shared_components/_flash_message.html.erb
<% flash.each do |type, message| %>
  <% bootstrap_class =
      case type.to_sym
      when :notice then "alert-success"
      when :alert  then "alert-danger"
      else "alert-info"
      end %>

  <div class="flash-container">
    <div class="alert <%= bootstrap_class %> alert-dismissible fade show" role="alert" id="flash-message-<%= SecureRandom.hex(4) %>">
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
  </div>
<% end %>

app/views/layouts/shared_components/_footer.html.erb
<footer class="w-100 d-flex flex-md-row flex-column align-items-center justify-content-center px-3 pt-4 pb-2" style="background-color: var(--bar-bg); gap: 4rem;">
    <!-- Col 1: Logo -->
    <%= image_tag "logo.png", alt: "LeanHouse Logo", class: "logo" %>

    <!-- Col 2: Main content: links + copyright -->
    <div class="d-flex flex-column flex-wrap gap-2">
        <!-- Row 1: main links + contact + logos -->
        <div class="main-links-container d-flex gap-5 pb-1">
        
            <!-- Links rows -->
            <div class="main-links d-flex flex-column flex-wrap align-items-start gap-2">
                <%= link_to root_path, class: "d-flex align-items-center gap-1" do %>
                <span class="icon material-symbols-filled">home</span>
                <%= t('bar.home') %>
                <% end %>
                <%= link_to t('common.bar.about'), about_path %>
                <%= link_to t('common.bar.features'), features_path %>
                <%= link_to t('common.bar.report_issues'), report_issues_path %>
            </div>

            <div class="main-links d-flex flex-column flex-wrap align-items-start gap-2">
                <%= link_to posts_path, class: "d-flex align-items-center gap-1" do %>
                <span class="icon material-symbols-filled">search</span>
                <%= t('common.bar.find_rooms') %>
                <% end %>
                <%= link_to t('common.bar.terms'), terms_of_use_path %>
                <%= link_to t('common.bar.privacy'), privacy_path %>
            </div>

            <!-- Contact -->
            <div class="main-links contact d-flex flex-column gap-1">
                <p class="mb-2"><%= t('common.bar.contact') %></p>
                <p><%= t('common.bar.company_name').upcase %></p>
                <p><%= t('common.bar.working_hours') %></p>
                <p class="d-flex align-items-center gap-1">
                <span class="material-symbols-filled">call</span>
                (+84) 123 456 789
                </p>
                <p class="d-flex align-items-center gap-1">
                <span class="material-symbols-filled">location_on</span>
                <%= t('bar.address') %>
                </p>
                <p class="d-flex align-items-center gap-1">
                <span class="material-symbols-filled">email</span>
                <a href="mailto:customerservice@LeanHouse.com">customerservice@LeanHouse.com</a>
                </p>
            </div>

            <!-- BCT Logos -->
            <div class="d-flex flex-column gap-3">
                <%= image_tag "da-thong-bao-bct.png", alt: t('bar.notified'), class: "notify-bct" %>
                <%= image_tag "da-dang-ky-bct.png", alt: t('bar.registered'), class: "reg-bct" %>
            </div>

        </div>

        <!-- Row 2: copyright -->
        <div class="muted-text w-100 text-center">
            <%= t('common.bar.copy_rights') %>
        </div>

    </div>
</footer>

app/views/layouts/shared_components/_header.html.erb
<nav class="navbar sticky-top navbar-expand-md navbar-light py-0">
  <div class="container-fluid px-4">

    <!-- Logo -->
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", alt: "LeanHouse Logo" %>
    <% end %>

    <!-- Nav links -->
    <%= render "layouts/shared_components/nav_link" %>

    <div class="d-flex gap-3 align-items-center">
        <%# User authentication links %>
      <%= render "layouts/shared_components/auth_box" %>

      <%# Language selector%>
      <div class="nav-item dropdown lang-switcher">
        <a class="nav-link lang-btn dropdown-toggle d-flex justify-content-center align-items-center gap-1"
                type="button"
                id="langDropdown"
                data-bs-toggle="dropdown"
                aria-expanded="false">
            <span class="material-symbols-outlined">language</span>
            <%= I18n.locale.to_s.upcase %> <!-- Current language -->
        </a>

        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="langDropdown">
            <% ["en", "vi"].each do |loc| %>
            <li>
                <%= link_to loc.upcase,
                            url_for(params.permit!.to_h.merge(lang: loc)),
                            class: "dropdown-item #{'active' if I18n.locale.to_s == loc}" %>
            </li>
            <% end %>
        </ul>
      </div>
    </div>

    <!-- Mobile toggle -->
    <button class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>  
</nav>

app/views/layouts/shared_components/_nav_link.html.erb
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto d-flex align-items-center gap-3">
    <%# TODO Authorize and insert the links %>
    <%if !logged_in?%>
        <%= nav_item t("common.bar.home"), "Home", path: root_path, icon: "home" %>
        <%= nav_item t("common.bar.find_rooms"), "Finding Rooms", path: posts_path, icon: "search" %>
        <%= nav_item t("common.bar.features"), "Features", path: features_path%>
        <%= nav_item t("common.bar.about"), "About", path: about_path %>
        <%= nav_item t("common.bar.contact"), "Contact", path: contact_path %>

    <%elsif current_user.role == "landlord"%>
        <%= nav_item t("common.bar.dashboard"), "Dashboard", path: landlord_dashboard_index_path, icon: "insert_chart" %>
        <%= nav_item t("common.bar.house_mng"), "House Management", word: "house", path: landlord_houses_path(current_user.id), is_img: true, img_src: "house-mg.png", img_active_src: "house-mg-white.png" %>
        <%= nav_item t("common.bar.post_mng"), "Post", path: landlord_posts_path(current_user.id)%>
        <%= nav_item t("common.bar.request_handle"), "Requests", path: about_path %>

    <%elsif current_user.role == "tenant"%>
        <%= nav_item t("common.bar.dashboard"), "Dashboard", path: tenant_dashboard_index_path(current_user.id), icon: "insert_chart" %>
        <%= nav_item t("common.bar.my_room"), "My Room", "#", icon: "location_home" %>
        <%= nav_item t("common.bar.my_contract"), "My Contract", path: "#"%>
        <%= nav_item t("common.bar.applied_services"), "Services", path: "#"%>
        <%= nav_item t("common.bar.my_invoices"), "My Invoices", path: "#" %>
        <%= nav_item t("common.bar.my_requests"), "My Requests", path: "#" %>
        <%= nav_item t("common.bar.find_rooms"), "Finding Rooms", path: posts_path, icon: "search" %>
    <%else%>

    <%end%>
    <!-- Dropdown 
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false">
        Dropdown
        </a>

        <ul class="dropdown-menu">
        <li><%= link_to "Action", "#", class: "dropdown-item" %></li>
        <li><%= link_to "Another action", "#", class: "dropdown-item" %></li>
        <li><hr class="dropdown-divider"></li>
        <li><%= link_to "Something else", "#", class: "dropdown-item" %></li>
        </ul>
    </li>
    -->
    </ul>
</div>